### ISSUE TITLE
A  keyboard  command for copy current url to clipboard

### ISSUE THREAD

**Issue by plum** [ric2b/Vivaldi-browser#11]
I find there isn't a command in Vivaldi, rather excellent browser, to copy current url to clipboard: Am I mistaken?

If true,  I would request this as a useful feature for writers of all kinds:
- From computer technicians through to students and professors as writers of all disciplines -arts and sciences. 
- Then there are the console-driven workers, who like to save urls to a command-line tool like tool, like Buku.

I cannot estimate accurately the amount of human time saved but nontheless, I shall have a go; By saving one keystroke, to accomplish the task, I.E. to first focus on the current url in the current open pane, a person may save 40 hours or a week in a lifetime. Multiply that by several Billion... that's a lot. (-:

Thanks,
John

**Comment by mathieucaroff** [comment]
Vivaldi is not developed here in this repository. This is just a user-maintained mirror of the sources that Vivaldi releases at [vivaldi.com/source](https://vivaldi.com/source/) . If you need help, support, to report an issue or to submit a feature request, use the Vivaldi forum: [forum.vivaldi.net/category/2/vivaldi-browser](https://forum.vivaldi.net/category/2/vivaldi-browser)
