### ISSUE TITLE
Website spelling error

### ISSUE THREAD

**Issue by thobiasvicente** [ric2b/Vivaldi-browser#12]
On https://vivaldi.com/pt-br/, has a small typo. it says "mensa", it should be "mensal".

![Screenshot 2022-02-15 100831](https://user-images.githubusercontent.com/26510258/154068415-ff2beac1-111b-4244-b6ba-51a2719f04da.png)

**Comment by mathieucaroff** [comment]
Vivaldi is not developed here in this repository. This is just a user-maintained mirror of the sources that Vivaldi releases at [vivaldi.com/source](https://vivaldi.com/source/) . If you need help, support, to report an issue or to submit a feature request, use the Vivaldi forum: [forum.vivaldi.net/category/2/vivaldi-browser](https://forum.vivaldi.net/category/2/vivaldi-browser)
