### ISSUE TITLE
Shortcut for Filter Invert stays permanent

### ISSUE THREAD

**Issue by i-zanis** [ric2b/Vivaldi-browser#13]
1. Add shortcut for filter invert
2. Press the shortcut combination
3. Close the browser
4. Restart Windows
5. Open Browser
6. Filter Invert is permanently active

**Comment by mathieucaroff** [comment]
Vivaldi is not developed here in this repository. This is just a user-maintained mirror of the sources that Vivaldi releases at [vivaldi.com/source](https://vivaldi.com/source/) . If you need help, support, to report an issue or to submit a feature request, use the Vivaldi forum: [forum.vivaldi.net/category/2/vivaldi-browser](https://forum.vivaldi.net/category/2/vivaldi-browser)
