### ISSUE TITLE
Shortcut bar open without a selected shortcut

### ISSUE THREAD

**Issue by BlazeItCoding** [ric2b/Vivaldi-browser#14]
Sometimes the Shortcut bar is open with just empty space.

**Comment by mathieucaroff** [comment]
Vivaldi is not developed here in this repository. This is just a user-maintained mirror of the sources that Vivaldi releases at [vivaldi.com/source](https://vivaldi.com/source/) . If you need help, support, to report an issue or to submit a feature request, use the Vivaldi forum: [forum.vivaldi.net/category/2/vivaldi-browser](https://forum.vivaldi.net/category/2/vivaldi-browser)
