### ISSUE TITLE
It freeze when I open incognito tab

### ISSUE THREAD

**Issue by MeftunH** [ric2b/Vivaldi-browser#15]
It does when I try to open first time.

**Comment by mathieucaroff** [comment]
Vivaldi is not developed here in this repository. This is just a user-maintained mirror of the sources that Vivaldi releases at [vivaldi.com/source](https://vivaldi.com/source/) . If you need help, support, to report an issue or to submit a feature request, use the Vivaldi forum: [forum.vivaldi.net/category/2/vivaldi-browser](https://forum.vivaldi.net/category/2/vivaldi-browser)
