### ISSUE TITLE
Wish list for Vivaldi

### ISSUE THREAD

**Issue by chazbroam** [ric2b/Vivaldi-browser#17]
1. I could use MY OWN Speeddial Extension, instead of Vivaldi's.
2. I could use MY OWN GTK theme (Linux).
3. I could sort the order of the visible extensions.
4. There was an IRC add-on, similar to the email feature.

**Comment by mathieucaroff** [comment]
Vivaldi is not developed here in this repository. This is just a user-maintained mirror of the sources that Vivaldi releases at [vivaldi.com/source](https://vivaldi.com/source/) . If you need help, support, to report an issue or to submit a feature request, use the Vivaldi forum: [forum.vivaldi.net/category/2/vivaldi-browser](https://forum.vivaldi.net/category/2/vivaldi-browser)
