### ISSUE TITLE
latest updates have completely ruined print.

### ISSUE THREAD

**Issue by sasori7** [ric2b/Vivaldi-browser#18]
my prints are mangled after the latest updates; 6.2 worked fine.
plus, updates are forced, so I can't just keep the version that works.  When I set not to update, it does it anyway.

**Comment by mathieucaroff** [comment]
Vivaldi is not developed here in this repository. This is just a user-maintained mirror of the sources that Vivaldi releases at [vivaldi.com/source](https://vivaldi.com/source/) . If you need help, support, to report an issue or to submit a feature request, use the Vivaldi forum: [forum.vivaldi.net/category/2/vivaldi-browser](https://forum.vivaldi.net/category/2/vivaldi-browser)
