### ISSUE TITLE
MacOS. Select drop-down, displayed outside iframe

### ISSUE THREAD

**Issue by iabai** [ric2b/Vivaldi-browser#2]
Hi!
On macOS Vivaldi display select dropdown outside iframe.
Reproduced on versions 10.13 and 10.14
You can see this bug here: https://jsfiddle.net/komjah/9kgwe6mn/

**Comment by mathieucaroff** [comment]
Hello @iabai. This repository is nothing official. ric2b and I, just thought it would be good to have a github mirror of the Vivaldi source available at https://vivaldi.com/source/.

Issues with Vivaldi are usually handled on the [Vivaldi forum](https://forum.vivaldi.net/).

Have a good day.

**Comment by iabai** [comment]
Thanks
