### ISSUE TITLE
Tab Tiling

### ISSUE THREAD

**Issue by anhIT195** [ric2b/Vivaldi-browser#20]
Hello sir, can I ask you a question? 
Does this source code has tab tiling function? As I know this feature of Vivaldi is blocked API.

**Comment by mathieucaroff** [comment]
Vivaldi is not developed here in this repository. This is just a user-maintained mirror of the sources that Vivaldi releases at [vivaldi.com/source](https://vivaldi.com/source/) . If you need help, support, to report an issue or to submit a feature request, use the Vivaldi forum: [forum.vivaldi.net/category/2/vivaldi-browser](https://forum.vivaldi.net/category/2/vivaldi-browser)
