### ISSUE TITLE
Vivaldi displays leetcode.com different from all other browsers

### ISSUE THREAD

**Issue by Rope-a-dope** [ric2b/Vivaldi-browser#21]
Just go to [leetcode](https://leetcode.com/problemset/), click any problem, you will see. It should has a format button like circled on the top right in the screenshot.  Chrome/FIrefox/Edge displays correctly with two panes if you click on Editorial/Solutions/Submissions and on the right side it has format button, the run code is on the top. All other browsers display like this except that Zen/Floorp doesn't display the forma button. However, Vivaldi is displaying leetcode.com like in a very ancient way: only one pane and no format button for code and the layout is just different from all other browsers.
![image](https://github.com/user-attachments/assets/00344b9a-75ca-437a-b19f-53500d557333)

This is Vivaldi, the layout I think is old layout of leetcode.
![image](https://github.com/user-attachments/assets/37704125-5967-484a-8239-2a77d6ecc220)
Just one pane, and there is no copy button for code block in the discussion.
![Screenshot_20240913_181729](https://github.com/user-attachments/assets/1a3e3735-9f01-4738-94a3-f55de966f5ed)

**Comment by mathieucaroff** [comment]
Vivaldi is not developed here in this repository. This is just a user-maintained mirror of the sources that Vivaldi releases at [vivaldi.com/source](https://vivaldi.com/source/) . If you need help, support, to report an issue or to submit a feature request, use the Vivaldi forum: [forum.vivaldi.net/category/2/vivaldi-browser](https://forum.vivaldi.net/category/2/vivaldi-browser)
