### ISSUE TITLE
Ugly csd deco

### ISSUE THREAD

**Issue by CavaleriOmar** [ric2b/Vivaldi-browser#3]
Would it be possible to have the option to choose minimize-maximize-close buttons? So that also in the csd mode it reflects the theme used by KDE?

**Comment by mathieucaroff** [comment]
Vivaldi is not developed here in this repository. This is just a user-maintained mirror of the sources that Vivaldi releases at https://vivaldi.com/source/ . If you need help, support, to report an issue or to submit a feature request, use the Vivaldi forum: https://forum.vivaldi.net/category/2/vivaldi-browser
