### ISSUE TITLE
Bitwarden AutoFill keyboard short cut does not work on Linux

### ISSUE THREAD

**Issue by stdcerr** [ric2b/Vivaldi-browser#4]
Hi,

I'm new to using Vivaldi and I have realized that the Bitwarden keyboard short cut to auto fill fields doesn't seem to work as it does in Firefox (Ctrl + Shift+ L) or as indicated on https://bitwarden.com/help/article/auto-fill-browser/. 
Am I missing a configuration option in Vilvaldi to enable this?
I am running:
$ vivaldi-stable --version
Vivaldi 3.1.1929.45 installed from the Arch AUR

**Comment by mathieucaroff** [comment]
Hello,

Vivaldi is not developed here in this repository. This is just a user-maintained mirror of the sources that Vivaldi releases at https://vivaldi.com/source/

You might have better luck with this issue at one of the two following places:

- https://github.com/bitwarden/browser/issues
- https://forum.vivaldi.net/category/2/vivaldi-browser

**Comment by stdcerr** [comment]
Alkriught, Thank you!
