### ISSUE TITLE
Disable console warning

### ISSUE THREAD

**Issue by zwhitchcox** [ric2b/Vivaldi-browser#9]
Is it possible to disable the console warning?

```
This is a browser feature intended for developers. If someone told you to copy-paste something here to enable a BirdEye feature or "hack" someone's account, it is a scam and will give them access to your BirdEye account.
```

As a developer, this is rather annoying.

**Comment by mathieucaroff** [comment]
Vivaldi is not developed here in this repository. This is just a user-maintained mirror of the sources that Vivaldi releases at https://vivaldi.com/source/ . If you need help, support, to report an issue or to submit a feature request, use the Vivaldi forum: https://forum.vivaldi.net/category/2/vivaldi-browser
